services:
  postgres:
    image: postgres:16-alpine
    container_name: barberboss-postgres-dev
    environment:
      POSTGRES_DB: barberboss
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d barberboss"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - barberboss-network-dev

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: builder
    container_name: barberboss-backend-dev
    environment:
      NODE_ENV: development
      DATABASE_URL: postgresql://admin:admin123@postgres:5432/barberboss
      PORT: 3000
    ports:
      - "3000:3000"
      - "9229:9229"
    volumes:
      - ./backend/src:/usr/src/app/src
      - ./backend/prisma:/usr/src/app/prisma
    command: ["sh", "-c", "npx prisma generate && npm run start:debug"]
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - barberboss-network-dev

  mobile:
    build:
      context: ./mobile
      dockerfile: Dockerfile
      target: development
    container_name: barberboss-mobile-dev
    environment:
      NODE_ENV: development
    ports:
      - "8100:8100"
    volumes:
      - ./mobile/src:/usr/src/app/src
    depends_on:
      - backend
    networks:
      - barberboss-network-dev

volumes:
  postgres_data_dev:
    driver: local

networks:
  barberboss-network-dev:
    driver: bridge
